#ifndef __BusApp_main_window__
#define __BusApp_main_window__

/**
@file
Subclass of main_window, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <pqxx/pqxx>
#include <vector>

/** Implementing main_window */
class BusApp_main_window : public main_window
{
	protected:
		// Handlers for main_window events.
		void mainOnClose( wxCloseEvent& event );
		void line_boxOnChoice( wxCommandEvent& event );
		void timetable_butOnButtonClick( wxCommandEvent& event );
		void beg_boxOnChoice( wxCommandEvent& event );
		void end_boxOnChoice( wxCommandEvent& event );
		void route_butOnButtonClick( wxCommandEvent& event );
		void bus_boxOnChoice( wxCommandEvent& event );
		void bus_butOnButtonClick( wxCommandEvent& event );
		void login_boxOnTextEnter( wxCommandEvent& event );
		void passwd_boxOnTextEnter( wxCommandEvent& event );
		void login_butOnButtonClick( wxCommandEvent& event );
		void table_print_boxOnChoice( wxCommandEvent& event );
		void print_butOnButtonClick( wxCommandEvent& event );
		void table_insert_boxOnChoice( wxCommandEvent& event );
		void insert_butOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		BusApp_main_window( wxWindow* parent);
	//// end generated class members

	void set_lines_list(size_t s, wxString* lst);
	void set_stops_list(size_t s, wxString* lst, std::vector<int> &ids);
	void set_buses_list(size_t s, wxString* lst);
	void add_line(wxString str);
	void add_stop(wxString str, int id);
	void add_bus(wxString str);
	void setConnection(pqxx::connection *C){this->C=C;}

	
	pqxx::connection *C;

	protected:
	bool loggedin = false;
	// int choice_line;

};

#endif // __BusApp_main_window__
