#ifndef __BusApp_Insertion__
#define __BusApp_Insertion__

/**
@file
Subclass of Insertion, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include



/** Implementing Insertion */
class BusApp_Insertion : public Insertion
{
	public:
		/** Constructor */
		BusApp_Insertion( wxWindow* parent );
	//// end generated class members

		virtual void save_ins_butOnButtonClick( wxCommandEvent& event );

















};

#endif // __BusApp_Insertion__
