#ifndef __BusApp_printout__
#define __BusApp_printout__

/**
@file
Subclass of printout, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing printout */
class BusApp_printout : public printout
{
	public:
		/** Constructor */
		BusApp_printout( wxWindow* parent );
	//// end generated class members


















};

#endif // __BusApp_printout__
